### ISSUE TITLE
WannaCry Ransomware Decryption Issue - '00000000.dky'

### ISSUE THREAD

**Issue by gregorytg** [gentilkiwi/wanadecrypt#6]
Can you please help on this issue, I have encountered.

We have paid the ransom amount of $300 and got a message from attackers like they have confirmed the payment(last week). 
But when I click 'Decrypt' and 'start' button.
The '@WanaDecryptor@.exe' application crashed and showing 'Load PerfMon Counters has stopped working'. And, I was not able to decrypt the files.
![payment](https://user-images.githubusercontent.com/15854177/27082680-52da3790-5063-11e7-99c4-2b0b13d0fdb2.png)
![error message](https://user-images.githubusercontent.com/15854177/27082685-58896eb8-5063-11e7-8cd2-f023cf453451.png)
Another issue, at the time of infection of ransomware, in C drive there was around 20 GB free space. 
But now, it shows automatically 'no free space'.So I thought because of this issue the decryption process has stopped. Then I deleted some of the unwanted files from C drive and then again ran the application. But, still the application has crashed.
The '@WanaDecryptor@.exe' application, I have restored it from the list of quarantined files.

Also, at the time of confirmation of payment, there is a file created namely - '00000000.dky'(Key created or dropped by ransomware authors)

Then, I used the wanadecrypt tool by gentilkiwi, but only very few files got decrypted. Most of the files it showing the error as shown below.
![wanadecrypt error](https://user-images.githubusercontent.com/15854177/27083019-bd1ef11c-5064-11e7-9f3f-1ec77f648f3f.jpg)

Operating System- Windows Server 2008 R2 Enterprise

**Comment by gentilkiwi** [comment]
Close a duplicate in: https://github.com/gentilkiwi/wanakiwi/issues/26
